# Generated by Django 2.1.7 on 2019-08-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='useless',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
