# Generated by Django 2.1.7 on 2019-08-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantom', '0002_account_useless'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='useless',
        ),
    ]
