# Generated by Django 2.1.7 on 2019-08-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantom', '0003_remove_account_useless'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
