image: node:10.15.1

pipelines:
  branches:
    staging:
      - step:
          name: Staging Deploy
          deployment: staging
          script:
            - yarn install
            - npm install create-react-app -g
            - yarn build
            - pipe: atlassian/aws-s3-deploy:0.2.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: "us-east-1"
                S3_BUCKET: "stagingapp.firecatapult.com"
                LOCAL_PATH: "build"
                ACL: "public-read"
                CACHE_CONTROL: "max-age=3600"
                EXPIRES: "2018-10-01T00:00:00+00:00"
                DELETE_FLAG: "true"
                EXTRA_ARGS: "--follow-symlinks"
    master:
      - step:
          name: Production Deploy
          deployment: production
          script:
            - yarn install
            - npm install create-react-app -g
            - yarn build
            - pipe: atlassian/aws-s3-deploy:0.2.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: "us-east-1"
                S3_BUCKET: "app.firecatapult.com"
                LOCAL_PATH: "build"
                ACL: "public-read"
                CACHE_CONTROL: "max-age=3600"
                EXPIRES: "2018-10-01T00:00:00+00:00"
                DELETE_FLAG: "true"
                EXTRA_ARGS: "--follow-symlinks"
