export const ROUTER_PUSH = 'ROUTER_PUSH'

export const LOGIN = 'LOGIN';
export const LOAD_USER = 'LOAD_USER';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const UPDATE_USER = 'UPDATE_USER';
export const UPLOAD_LOGO = 'UPLOAD_LOGO';

export const LOAD_SERIES = 'LOAD_SERIES';
export const LOAD_SERIES_SINGULAR = 'LOAD_SERIES_SINGULAR';
export const LOAD_MORE_SERIES = 'LOAD_MORE_SERIES';
export const LOAD_FILTERS = 'LOAD_FILTERS'

export const LOAD_VIDEOS = 'LOAD_VIDEOS';
export const LOAD_VIDEO = 'LOAD_VIDEO';
export const LOAD_MORE_VIDEOS = 'LOAD_MORE_VIDEOS';
export const LOAD_CUSTOMIZED_VIDEO = 'LOAD_CUSTOMIZED_VIDEO';

export const LOAD_SUBSCRIPTIONS = 'LOAD_SUBSCRIPTIONS';
export const LOAD_MORE_SUBSCRIPTIONS = 'LOAD_MORE_SUBSCRIPTIONS';
export const SUBSCRIBE = 'SUBSCRIBE';
export const UNSUBSCRIBE = 'UNSUBSCRIBE';